In [8]:

pip install pandas matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.7.2)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [11]:
import pandas as pd

In [20]:
df = pd.read_excel("C:\DATA SCIENCE ASSIGNMENTS\INNOVEXIS_Intern Projects\Projects of intern\Ola\OLA_DataSet.xlsx")

In [22]:
df.head(5)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,NaN

In [23]:
#basic data understanding
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              0 non-null       float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(12)
memory usage: 15.7+ MB

,Date,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
count,103024,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000,0.0
mean,2024-07-16 11:31:38.879678720,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313,NaN
min,2024-07-01 00:00:00,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000,NaN
25%,2024-07-08 18:41:00,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000,NaN
50%,2024-07-16 11:23:00,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000,NaN
75%,2024-07-24 05:18:00,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000,NaN
max,2024-07-31 23:58:00,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000,NaN
std,NaN,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957,NaN

In [24]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Date,103024,NaN,NaN,NaN,2024-07-16 11:31:38.879678720,2024-07-01 00:00:00,2024-07-08 18:41:00,2024-07-16 11:23:00,2024-07-24 05:18:00,2024-07-31 23:58:00,NaN
Time,103024,1440,00:53:00,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Booking_ID,103024,103024,CNR7153255142,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Booking_Status,103024,4,Success,63967,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_ID,103024,94544,CID954071,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vehicle_Type,103024,7,Prime Sedan,14877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pickup_Location,103024,50,Banashankari,2201,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Drop_Location,103024,50,Peenya,2159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
V_TAT,63967.0,NaN,NaN,NaN,170.876952,35.0,98.0,168.0,238.0,308.0,80.80364
C_TAT,63967.0,NaN,NaN,NaN,84.873372,25.0,55.0,85.0,115.0,145.0,36.0051
Canceled_Rides_by_Customer,10499,5,Driver is not moving towards pickup location,3175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canceled_Rides_by_Driver,18434,4,Personal & Car related issue,6542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Incomplete_Rides,63967,2,No,60041,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Incomplete_Rides_Reason,3926,3,Customer Demand,1601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Booking_Value,103024.0,NaN,NaN,NaN,548.751883,100.0,242.0,386.0,621.0,2999.0,536.541221
Payment_Method,63967,4,Cash,35022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ride_Distance,103024.0,NaN,NaN,NaN,14.189927,0.0,0.0,8.0,26.0,49.0,15.77627
Driver_Ratings,63967.0,NaN,NaN,NaN,3.997457,3.0,3.5,4.0,4.5,5.0,0.576834
Customer_Rating,63967.0,NaN,NaN,NaN,3.998313,3.0,3.5,4.0,4.5,5.0,0.578957
Vehicle Images,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Summary statistics for categorical data
df.describe(include = 'object')

,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Payment_Method,Driver_Ratings,Customer_Rating,Vehicle Images
count,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024,103024
unique,1440,103024,4,94544,7,50,50,41,26,6,5,3,4,5,22,22,1
top,00:53:00,CNR7153255142,Success,CID954071,Prime Sedan,Banashankari,Peenya,Not Available,Not Available,Not Available,Not Available,No,Not Available,Not Available,Not Available,Not Available,Not Available
freq,101,1,63967,5,14877,2201,2159,39057,39057,92525,84590,60041,99098,39057,39057,39057,103024

In [25]:
#Handling missing values
df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          39057
C_TAT                          39057
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                 39057
Customer_Rating                39057
Vehicle Images                103024
dtype: int64

In [26]:
df.isnull().sum()/len(df)* 100

Date                            0.000000
Time                            0.000000
Booking_ID                      0.000000
Booking_Status                  0.000000
Customer_ID                     0.000000
Vehicle_Type                    0.000000
Pickup_Location                 0.000000
Drop_Location                   0.000000
V_TAT                          37.910584
C_TAT                          37.910584
Canceled_Rides_by_Customer     89.809171
Canceled_Rides_by_Driver       82.107082
Incomplete_Rides               37.910584
Incomplete_Rides_Reason        96.189237
Booking_Value                   0.000000
Payment_Method                 37.910584
Ride_Distance                   0.000000
Driver_Ratings                 37.910584
Customer_Rating                37.910584
Vehicle Images                100.000000
dtype: float64

In [27]:
df.fillna("Not Available", inplace = True)

In [28]:
df.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
Vehicle Images                0
dtype: int64

In [29]:
#Removing duplicates
df.duplicated().sum()

0

In [30]:
# Displays if there is duplicated rows
df[df.duplicated()]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating, Vehicle Images]
Index: []

In [ ]:
## Explore key business metrics

In [41]:
Total_rides = len(df)
print(Total_rides)

103024

In [45]:
Booking_status = df['Booking_Status'].value_counts()
print(Booking_status)

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [48]:
Revenue = df['Booking_Value'].sum()
print(Revenue)

56534614

In [65]:
# Rating analysis
# Changing the data type object to numeric
df['Customer_Rating'] = pd.to_numeric(df['Customer_Rating'], errors = 'coerce')
df['Driver_Ratings'] = pd.to_numeric(df['Driver_Ratings'], errors = 'coerce')

In [64]:
df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
V_TAT                                 object
C_TAT                                 object
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
Vehicle Images                        object
dtype: object

In [74]:
#Rating Analysis
Customer_ratings = df['Customer_Rating'].mean()
print(Customer_ratings)
Driver_ratings = df['Driver_Ratings'].mean()
print(Driver_ratings)

3.9983131927400057
3.9974565010083327

In [75]:
print("Average Customer Rating :" ,round(Customer_ratings,2))
print("Average Driver Rating :" , round(Driver_ratings,2))

Average Customer Rating : 4.0
Average Driver Rating : 4.0

In [77]:
Average_bookingvalue = df['Booking_Value'].mean()
print(Average_bookingvalue)

548.7518830563752

In [78]:
Vehicletype_analysis  = df.groupby('Vehicle_Type')['Booking_Value'].sum()
print(Vehicletype_analysis)

Vehicle_Type
Auto           8092210
Bike           7987054
Mini           7990996
Prime Plus     8050889
Prime SUV      7933330
Prime Sedan    8298612
eBike          8181523
Name: Booking_Value, dtype: int64

In [89]:
Paymentmethod_analysis = df['Payment_Method'].value_counts()
print(Paymentmethod_analysis)

Payment_Method
Not Available    39057
Cash             35022
UPI              25881
Credit Card       2435
Debit Card         629
Name: count, dtype: int64

In [94]:

df['Booking_Status'].unique()

array(['Canceled by Driver', 'Success', 'Canceled by Customer',
       'Driver Not Found'], dtype=object)

In [105]:
Customer_Cancellation_reason = df[df['Booking_Status'] == 'Canceled by Customer'][
    'Canceled_Rides_by_Customer'
].value_counts()

print(Customer_Cancellation_reason)

Canceled_Rides_by_Customer
Driver is not moving towards pickup location    3175
Driver asked to cancel                          2670
Change of plans                                 2081
AC is Not working                               1568
Wrong Address                                   1005
Name: count, dtype: int64

In [106]:
Driver_cancellation_reason = df[df['Booking_Status'] == 'Canceled by Driver'][
    'Canceled_Rides_by_Driver'
].value_counts()

print(Driver_cancellation_reason)

Canceled_Rides_by_Driver
Personal & Car related issue           6542
Customer related issue                 5413
Customer was coughing/sick             3654
More than permitted people in there    2825
Name: count, dtype: int64

In [118]:
# Extract Hour
df['Hour'] = df['Time'].apply(lambda x: x.hour)
df['Hour'].head()

0    14
1    22
2    19
3     3
4     9
Name: Hour, dtype: int64

In [120]:
# Create time slot
def time_slot(x):
    if 6 <= x <= 11:
        return 'Morning'
    elif 12 <= x <= 16:
        return 'Afternoon'
    elif 17 <= x <= 21:
        return 'Evening'
    else:
        return 'Night'

df['time_slot'] = df['Hour'].apply(time_slot)

In [121]:
df.groupby('time_slot').size()

time_slot
Afternoon    21562
Evening      21371
Morning      25902
Night        34189
dtype: int64

In [122]:
# save cleaned data
df.to_csv("cleaned_ola_data.csv", index = False)

In [125]:
# to check the file path when you dont know exactly
import os 
os.getcwd()

'C:\\Users\\revat'

In [126]:
file_path = r"C:\DATA SCIENCE ASSIGNMENTS\INNOVEXIS_Intern Projects\Projects of intern\Ola\Cleaned_ola_data.csv"
df.to_csv(file_path, index = False)

In [13]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\revat\appdata\roaming\python\python311\site-packages (9.6.0)

In [1]:
import pandas as pd
import mysql.connector

# Read CSV
df = pd.read_csv("cleaned_ola_data.csv")

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="your_password",
    database="ola_project"
)

cursor = conn.cursor()

# Insert Data
for i,row in df.iterrows():
    sql = """INSERT INTO ola_data 
             (Date, Time, Booking_ID, Booking_Status)
             VALUES (%s,%s,%s,%s)"""
    
    cursor.execute(sql, tuple(row[:4]))  # adjust columns

conn.commit()
conn.close()

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [14]:
import pandas as pd
import mysql.connector

# Read CSV
df = pd.read_csv("cleaned_ola_data.csv")

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Revathi@9812",
    database="ola_analysis"
) 

print("Connected Successfully!")

conn.close()

Connected Successfully!

In [15]:
pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (1.4.39)
Collecting pymysql
  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/7c/4c/ad33b92b9864cbde84f259d5df035a6447f91891f5be77788e2a3892bce3/pymysql-1.1.2-py3-none-any.whl.metadata
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.3 kB ? eta -:--:--
   --------------------------- ------------ 30.7/45.3 kB 325.1 kB/s eta 0:00:01
   ---------------------------------------- 45.3/45.3 kB 373.0 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd
from sqlalchemy import create_engine

# Read CSV
df = pd.read_csv("cleaned_ola_data.csv")

# Create connection engine
engine = create_engine("mysql+pymysql://root:Revathi@9812@localhost/ola_analysis")

# Push dataframe to MySQL
df.to_sql(
    name="cleaned_ola_data",   # table name
    con=engine,
    if_exists="replace",       # replace if already exists
    index=False
)

print("Data uploaded successfully!")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '9812@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [17]:
from sqlalchemy import create_engine
import urllib.parse

password = urllib.parse.quote_plus("Revathi@9812")

engine = create_engine(f"mysql+pymysql://root:{password}@localhost/ola_analysis")

In [18]:
df.to_sql(
    name="cleaned_ola_data",
    con=engine,
    if_exists="replace",
    index=False
)

103024